export const products = [
  {
    id: "1",
    brandName: "God Bless",
    title: "Women Floral Pant",
    imgUrl: "https://picsum.photos/400/500?random=1",
    isSponsored: true,
    isAssured: true,
    actualPrice: 999,
    discount: 50,
    currentPrice: 500,
    currency: "INR",
    sizes: ["S", "M", "L"],
    colors: ["White", "Blue", "Pink"],
    productStatus: "Hot deal",
  },
  {
    id: "2",
    brandName: "Urban Threads",
    title: "Men Slim Fit Jeans",
    imgUrl: "https://picsum.photos/400/500?random=2",
    isSponsored: false,
    isAssured: true,
    actualPrice: 1499,
    discount: 40,
    currentPrice: 899,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Gray"],
    productStatus: "Trending",
  },
  {
    id: "3",
    brandName: "StyleWave",
    title: "Women Cotton Kurti",
    imgUrl: "https://picsum.photos/400/500?random=3",
    isSponsored: true,
    isAssured: false,
    actualPrice: 1299,
    discount: 45,
    currentPrice: 715,
    currency: "USD",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Green", "Yellow"],
    productStatus: "Best Seller",
  },
  {
    id: "4",
    brandName: "Metro Fashion",
    title: "Men Casual Shirt",
    imgUrl: "https://picsum.photos/400/500?random=4",
    actualPrice: 999,
    discount: 30,
    currentPrice: 699,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Blue", "White"],
    productStatus: "Hot deal",
  },
  {
    id: "5",
    brandName: "TrendX",
    title: "Women High Waist Jeans",
    imgUrl: "https://picsum.photos/400/500?random=5",
    actualPrice: 1899,
    discount: 50,
    currentPrice: 949,
    currency: "INR",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy"],
    productStatus: "Limited",
  },
  {
    id: "6",
    brandName: "CityWear",
    title: "Men Checkered Shirt",
    imgUrl: "https://picsum.photos/400/500?random=6",
    actualPrice: 1199,
    discount: 35,
    currentPrice: 780,
    currency: "INR",
    sizes: ["M", "L"],
    colors: ["Red", "Blue"],
    productStatus: "New Arrival",
  },
  {
    id: "7",
    brandName: "FashionArmy",
    title: "Women Printed Top",
    imgUrl: "https://picsum.photos/400/500?random=7",
    actualPrice: 799,
    discount: 20,
    currentPrice: 640,
    currency: "INR",
    sizes: ["S", "M"],
    colors: ["Pink", "Black"],
    productStatus: "Trending",
  },
  {
    id: "8",
    brandName: "RoyalFit",
    title: "Men Joggers",
    imgUrl: "https://picsum.photos/400/500?random=8",
    actualPrice: 1299,
    discount: 25,
    currentPrice: 975,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Gray", "Black"],
    productStatus: "Hot deal",
  },
  {
    id: "9",
    brandName: "EliteWear",
    title: "Women A-Line Dress",
    imgUrl: "https://picsum.photos/400/500?random=9",
    actualPrice: 1799,
    discount: 55,
    currentPrice: 810,
    currency: "INR",
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Maroon"],
    productStatus: "Best Seller",
  },
  {
    id: "10",
    brandName: "BoldLook",
    title: "Men Oversized T-Shirt",
    imgUrl: "https://picsum.photos/400/500?random=10",
    actualPrice: 699,
    discount: 10,
    currentPrice: 630,
    currency: "INR",
    sizes: ["L", "XL"],
    colors: ["White", "Black"],
    productStatus: "Trending",
  },
  {
    id: "11",
    brandName: "VogueMint",
    title: "Women Palazzo Pants",
    imgUrl: "https://picsum.photos/400/500?random=11",
    actualPrice: 999,
    discount: 40,
    currentPrice: 599,
    currency: "INR",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Brown"],
    productStatus: "Hot deal",
  },
  {
    id: "12",
    brandName: "UrbanEdge",
    title: "Men Cargo Pants",
    imgUrl: "https://picsum.photos/400/500?random=12",
    actualPrice: 1599,
    discount: 30,
    currentPrice: 1120,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Olive", "Black"],
    productStatus: "Limited Stock",
  },
  {
    id: "13",
    brandName: "GlowStyle",
    title: "Women Ethnic Skirt",
    imgUrl: "https://picsum.photos/400/500?random=13",
    actualPrice: 1499,
    discount: 50,
    currentPrice: 749,
    currency: "INR",
    sizes: ["S", "M", "L"],
    colors: ["Pink", "Yellow"],
    productStatus: "Festival Offer",
  },
  {
    id: "14",
    brandName: "DenimHub",
    title: "Men Straight Fit Jeans",
    imgUrl: "https://picsum.photos/400/500?random=14",
    actualPrice: 1999,
    discount: 45,
    currentPrice: 1100,
    currency: "INR",
    sizes: ["L", "XL"],
    colors: ["Blue"],
    productStatus: "Best Seller",
  },
  {
    id: "15",
    brandName: "StyleNest",
    title: "Women Crop Top",
    imgUrl: "https://picsum.photos/400/500?random=15",
    actualPrice: 699,
    discount: 15,
    currentPrice: 594,
    currency: "INR",
    sizes: ["S", "M"],
    colors: ["Black", "White"],
    productStatus: "Trending",
  },
  {
    id: "16",
    brandName: "AlphaWear",
    title: "Men Formal Shirt",
    imgUrl: "https://picsum.photos/400/500?random=16",
    actualPrice: 1399,
    discount: 35,
    currentPrice: 909,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Sky Blue"],
    productStatus: "Hot deal",
  },
  {
    id: "17",
    brandName: "CharmAura",
    title: "Women Long Kurta",
    imgUrl: "https://picsum.photos/400/500?random=17",
    actualPrice: 1599,
    discount: 45,
    currentPrice: 880,
    currency: "INR",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Blue"],
    productStatus: "Best Seller",
  },
  {
    id: "18",
    brandName: "FitLine",
    title: "Men Sports Shorts",
    imgUrl: "https://picsum.photos/400/500?random=18",
    actualPrice: 799,
    discount: 20,
    currentPrice: 640,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Navy"],
    productStatus: "Trending",
  },
  {
    id: "19",
    brandName: "RoyalChic",
    title: "Women Printed Saree",
    imgUrl: "https://picsum.photos/400/500?random=19",
    actualPrice: 2499,
    discount: 60,
    currentPrice: 999,
    currency: "INR",
    sizes: [],
    colors: ["Red", "Blue"],
    productStatus: "Hot deal",
  },
  {
    id: "20",
    brandName: "EverTrend",
    title: "Men Henley T-Shirt",
    imgUrl: "https://picsum.photos/400/500?random=20",
    actualPrice: 899,
    discount: 25,
    currentPrice: 675,
    currency: "INR",
    sizes: ["M", "L"],
    colors: ["Maroon", "Olive"],
    productStatus: "Limited",
  },
  {
    id: "21",
    brandName: "DreamWear",
    title: "Women Night Suit",
    imgUrl: "https://picsum.photos/400/500?random=21",
    actualPrice: 1299,
    discount: 40,
    currentPrice: 780,
    currency: "INR",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purple", "Pink"],
    productStatus: "Trending",
  },
  {
    id: "22",
    brandName: "CasualKing",
    title: "Men Polo T-Shirt",
    imgUrl: "https://picsum.photos/400/500?random=22",
    actualPrice: 1199,
    discount: 20,
    currentPrice: 960,
    currency: "INR",
    sizes: ["L", "XL"],
    colors: ["Blue", "White"],
    productStatus: "New Arrival",
  },
  {
    id: "23",
    brandName: "GlowFit",
    title: "Women Yoga Leggings",
    imgUrl: "https://picsum.photos/400/500?random=23",
    actualPrice: 999,
    discount: 30,
    currentPrice: 699,
    currency: "INR",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gray"],
    productStatus: "Hot deal",
  },
  {
    id: "24",
    brandName: "StreetMode",
    title: "Men Graphic Hoodie",
    imgUrl: "https://picsum.photos/400/500?random=24",
    actualPrice: 1999,
    discount: 40,
    currentPrice: 1199,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "White"],
    productStatus: "Best Seller",
  },
  {
    id: "25",
    brandName: "EthnicRoots",
    title: "Women Anarkali Kurta",
    imgUrl: "https://picsum.photos/400/500?random=25",
    actualPrice: 1799,
    discount: 50,
    currentPrice: 900,
    currency: "INR",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Pink"],
    productStatus: "Festival Offer",
  },
  {
    id: "26",
    brandName: "FlexFit",
    title: "Men Track Pants",
    imgUrl: "https://picsum.photos/400/500?random=26",
    actualPrice: 1299,
    discount: 25,
    currentPrice: 974,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Navy", "Black"],
    productStatus: "Trending",
  },
  {
    id: "27",
    brandName: "PrettyMode",
    title: "Women Denim Skirt",
    imgUrl: "https://picsum.photos/400/500?random=27",
    actualPrice: 1199,
    discount: 35,
    currentPrice: 780,
    currency: "INR",
    sizes: ["S", "M"],
    colors: ["Blue"],
    productStatus: "New Arrival",
  },
  {
    id: "28",
    brandName: "PrimeWear",
    title: "Men Sleeveless Jacket",
    imgUrl: "https://picsum.photos/400/500?random=28",
    actualPrice: 2499,
    discount: 45,
    currentPrice: 1375,
    currency: "INR",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Brown"],
    productStatus: "Hot deal",
  },
  {
    id: "29",
    brandName: "SoftNest",
    title: "Women Winter Sweater",
    imgUrl: "https://picsum.photos/400/500?random=29",
    actualPrice: 1999,
    discount: 50,
    currentPrice: 999,
    currency: "INR",
    sizes: ["S", "M", "L"],
    colors: ["Cream", "Pink"],
    productStatus: "Best Seller",
  },
  {
    id: "30",
    brandName: "NovaTrend",
    title: "Men Printed Shirt",
    imgUrl: "https://picsum.photos/400/500?random=30",
    actualPrice: 1299,
    discount: 30,
    currentPrice: 909,
    currency: "INR",
    sizes: ["M", "L"],
    colors: ["White", "Blue"],
    productStatus: "Trending",
  },
  {
    id: "31",
    brandName: "WaveWear",
    title: "Women Straight Pants",
    imgUrl: "https://picsum.photos/400/500?random=31",
    actualPrice: 1499,
    discount: 40,
    currentPrice: 899,
    currency: "INR",
    sizes: ["S", "M", "L"],
    colors: ["Beige", "Black"],
    productStatus: "Hot deal",
  },
];
